travis:
  secure:
    BINSTAR_TOKEN: Ctzj4Cf+KQUYqUjRLxq76Nxs92zx6uw9uxW3/5V/hIboCfqQ6eH6h3HE8lsafvruBBRNFpupC0n0G5ZVrqqzsoyniovm/FbNof+HIrMC2D1eXLc7woAKipHJWLmnESygwNPTF85QYzebFxJR+mJa4MBbBMJnYWLUsMlxLn1b9sYYyRodPye8bZHH0V+hOpirqo1PUzjxzH+7ZnF8iEl4LRQWoMlaXYrLuoymkLt76r4MrrH7FXtuTkn7UsOozyHwoZvDWbMLoWy5/iBJ6w67lAOdoODeNAKT4M3y51Ww0MD4RyBiqYhV3WuXqh/1/RTxP9PfsI/3ZVirv1gS8q5TFk3toLDuVNG2Jk2Bxz/Lr2hFeJtAIdIM2Yr5gMe9leeNDkii/ylWKY0H1IKkiD0iOzNcUUjQuMkUq/7OHuAF7vmQinpog/w2fbUdC/YU4/FfIkUeik0eLpdg44ABrKsXoNRi7kL8AroIEeqsQSI86QGPPqj8EuZ57fVAIO/SZk/i0bf/n2Rl/3bEprta9GQJPOc35Qrp9RoMOIuDstRYRWG/Brkx+lmPUR5/Lmx0hwYET+oSuKGSNWCZOUZvKHiPCzv+Fp4o+lcJz3PmtcDOHr8R0MyzGh+uhVC0XoVSEteOCnRtfhHesrg3ta2lkdYmZrZUBF8OQwrQTcMEWa5w0ew=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
