travis:
  secure:
    BINSTAR_TOKEN: V/ylGdCP5KxvpYigMXIvQSunt7w7op2Q1aIa1S/+S/paJB3PXhgYm4ZH/plKIl3DIsDt+tJy4Ah8qTQ/tlXAx1DJ3ScZcrbc/rOgMGROZosxA8XADqjtqwTAnZIuxZnmG3sCwCZyVDBjLOCP46pII8b3RIpEU6GUMVGWfWqTjoUt2i0hV0WbTpAWdDCKsdHhzI5Ge84Tkndk6jRekKwdThHvo32/YGurtJ5vDeS1tftZmJdWGQDjVPdQVB5neYrYVcXXMPwJbawGc5eVu6Rqnr7vKKV+wLgwN/ZlpO7DvCVGDhuBAUc+M4brvrAdcRy1V0ege1ZJb2NsyUaEgUYwiv9JotBZHunXjnuNqhdlHC9O4FmZaA9bjdTYXu+N6ZgQ8AX1lnHwKhHtlQvvGSw+LaS9gkq/uMW9KKZ0RuTiJV2mz0Rjz9spMjnUxXcZfXc1h5y5q/pxDVomudnnpPI9f4pb28SLoLMIJtnKYT3r6G96HfkFvBkYBB5D2yJ2KhXC5IIMChnuMQ2fKvbNREOo8epqQpbDZB6hCfM4HAstGYJaob4BrqGJxvKRDl0VHdpneA8ulfm1ks+P1ZGPagKO1qc1xAuB5/tkReChNJI9WG9htB/QkAwrUx0YSE48FflaFE1s0zb++hvOT4+85H8ICTo5g+UIyDDXE5ALVc+V/wc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
